name: Deploy to S3

on:
  push:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
  DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.120.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install -y curl unzip jq
          echo "Installing aws-cli"
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}

      - name: Build
        run: hugo --minify
        
      - name: Deploy to S3
        run: hugo deploy
        
      - name: Invalidate caches
        run: |
          echo "Invalidating caches"         
          response=$(aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*" | jq ".Invalidation.Status")
          echo "Invalidation status: $response"
          
